### ISSUE TITLE
SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure Python 2.6

### ISSUE THREAD

**Issue by khieu** [paypal/PayPal-Python-SDK#225]
### General information

* SDK/Library version: 
paypalrestsdk 1.13.1
* Environment: 
Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 
Python 2.6, Mac OS Sierra 10.12.6

### Issue description
I'm testing out the Payouts API through basic setup with client_id and client_secrets, then make a call to Payout just like the example in this link https://github.com/paypal/PayPal-Python-SDK/blob/master/samples/payout/create_single_payout.py
When I run the script, I get this error:
`raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:493: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`

I have tried a few things such as updating OpenSSL to version 1.0.2, reinstall requests with `[security]` option, I also verified my python and TLS version through this instruction:
https://github.com/paypal/tls-update#python
and get `PayPal_Connection_OK`.
However I still get the same alert handshake failure.

I want to ask if it's possible to resolve this issue without updating to python 2.7 ?

Thanks!

**Comment by xiaoleih41** [comment]
Are you using Mac?

**Comment by xiaoleih41** [comment]
After doing some research, we found out that Python 2.6 does have issues with TLS. You may have to upgrade to Python 2.7 because of that.

**Comment by khieu** [comment]
yeah I am using a Mac. I have done some searches and they suggest to upgrade to python 2.7 as well. Just wondering if there's anyway to make it work with python 2.6. If not I will probably have to to upgrade to 2.7.

**Comment by xiaoleih41** [comment]
Yeah before you upgrade, you may try this direction too: So the default version of cURL that's installed on OS X is built against SecureTransport and not OpenSSL, I think you can get a version of cURL from HomeBrew/MacPorts that's built against OpenSSL to see if it will solve. If not, please upgrade to 2.7

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.
